anchor_version = "0.30.2"
solana_version = "1.18.12"

[workspace]
members = [
    "stable-swap-anchor",
    "stable-swap-client",
    "stable-swap-math",
    "stable-swap-math/sim",
    "stable-swap-program/program",
]
exclude = ["fuzz"]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
stable_swap = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"

[programs.devnet]
stable_swap = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"

[programs.testnet]
stable_swap = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"

[programs.localnet]
stable_swap = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"
